packages:
    alptech/wip: v0.0.546
    dragonmantank/cron-expression: v3.1.0
    drush/drush: 6.0.0
    ezyang/htmlpurifier: v4.13.0
    guzzlehttp/guzzle: 7.3.0
    guzzlehttp/promises: 1.4.1
    guzzlehttp/psr7: 1.8.1
    imangazaliev/didom: 1.16.3
    maennchen/zipstream-php: 2.1.0
    markbaker/complex: 2.0.0
    markbaker/matrix: 2.1.2
    mikehaertl/php-shellcommand: 1.6.4
    mikehaertl/php-tmpfile: 1.2.1
    mikehaertl/phpwkhtmltopdf: 2.5.0
    myclabs/php-enum: 1.8.0
    peppeocchi/php-cron-scheduler: v3.1
    phpoffice/phpspreadsheet: 1.17.1
    psr/http-client: 1.0.1
    psr/http-factory: 1.0.1
    psr/http-message: 1.0.1
    psr/simple-cache: 1.0.1
    ralouphie/getallheaders: 3.0.3
    symfony/polyfill-ctype: v1.22.1
    symfony/polyfill-mbstring: v1.22.1
    webmozart/assert: 1.10.0
